FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* yarn.lock* ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_ENDPOINT
ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_CLOUDFRONT_BASE_URL
ARG NEXT_PUBLIC_WASABI_BUCKET_NAME

ENV NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT} \
    NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL} \
    NEXT_PUBLIC_CLOUDFRONT_BASE_URL=${NEXT_PUBLIC_CLOUDFRONT_BASE_URL} \
    NEXT_PUBLIC_WASABI_BUCKET_NAME=${NEXT_PUBLIC_WASABI_BUCKET_NAME}

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/package.json ./
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]

