version: "3.8"
services:
  ${services_0}:
    build:
      context: ./Backend/ApiGateway
      dockerfile: Dockerfile
    image: ${services_0}
    container_name: ${services_0}

  ${services_1}:
    build:
      context: ./Backend/Microservices.AspNet
      dockerfile: ./User.Microservice/Dockerfile
      args:
        SERVICE_NAME: User.Microservice
    image: ${services_1}
    container_name: ${services_1}

  ${services_2}:
    build:
      context: ./Terraform/docker/redis
      dockerfile: ./Dockerfile
    image: ${services_2}
    container_name: ${services_2}

  ${services_3}:
    build:
      context: ./Terraform/docker/rabbitmq
      dockerfile: ./Dockerfile
    image: ${services_3}
    container_name: ${services_3}   
