
services:
  api-gateway:
    build:
      context: ./Backend/ApiGateway
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "2406:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      OCELOT_BASE_URL: http://localhost:8080

      ROUTE_1_UPSTREAM_PATH: /api/user/{everything}
      ROUTE_1_UPSTREAM_METHODS: Get,Post,Put,Delete
      ROUTE_1_DOWNSTREAM_HOST: user-microservice
      ROUTE_1_DOWNSTREAM_PORT: 5002
      ROUTE_1_DOWNSTREAM_PATH: /api/user/{everything}

      ROUTE_2_UPSTREAM_PATH: /api/auth/{everything}
      ROUTE_2_UPSTREAM_METHODS: Get,Post,Put,Delete
      ROUTE_2_DOWNSTREAM_HOST: identity-microservice
      ROUTE_2_DOWNSTREAM_PORT: 5001
      ROUTE_2_DOWNSTREAM_PATH: /api/auth/{everything}

      ROUTE_3_UPSTREAM_PATH: /api/resource/{everything}
      ROUTE_3_UPSTREAM_METHODS: Get,Post,Put,Delete
      ROUTE_3_DOWNSTREAM_HOST: resource-microservice
      ROUTE_3_DOWNSTREAM_PORT: 5003
      ROUTE_3_DOWNSTREAM_PATH: /api/resource/{everything}

      ROUTE_4_UPSTREAM_PATH: /api/post/{everything}
      ROUTE_4_UPSTREAM_METHODS: Get,Post,Put,Delete
      ROUTE_4_DOWNSTREAM_HOST: post-microservice
      ROUTE_4_DOWNSTREAM_PORT: 8091
      ROUTE_4_DOWNSTREAM_PATH: /api/v1/posts/{everything}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq-data:
  redis-data: