FROM nginx:latest

# Copy static content into Nginx default directory
COPY index.html /usr/share/nginx/html/index.html

# Ensure proper permissions
RUN chmod -R 755 /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
