spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: post-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 0Kg04Rq08!